In [7]:
import torch
from torch.nn import functional as F

In [8]:
pred=torch.rand(1)
pred

tensor([0.3376])

In [9]:
probabilities=F.softmax(pred, dim=0)
probabilities,probabilities

(tensor([1.]), torch.Size([1]))

In [10]:
action_index = torch.distributions.Categorical(probabilities).sample()
action_index

tensor(0)

In [11]:
probs = probabilities.gather(0, action_index)
probs

tensor(1.)

In [14]:
a = torch.rand(2, 3)
a.reshape(-1)

tensor([0.9890, 0.1259, 0.5043, 0.6915, 0.3374, 0.7802])

In [17]:
a = torch.tensor(
    [
        [
            1.0,
        ]
    ]
)

In [24]:
F.softmax(a, dim=0).squeeze().reshape(-1).shape

tensor([1.])